ArUcoサンプルとピッキング動作の追加
rt-net/crane_x7_ros pull request #169
Opened 2022-12-28 09:37 UTC by Kuwamai

# What does this implement/fix?

把持対象に取り付けられたArUcoマーカの位置を認識し、把持対象をピックアンドプレースするサンプルです

# Does this close any currently open issues?

しません

# How has this been tested?

RealSense搭載モデルのX7をPCと接続し、下記コマンドを実行します。

```
ros2 launch crane_x7_examples demo.launch.py use_d435:=true
ros2 launch crane_x7_examples camera_example.launch.py example:='aruco_detection'
```

ArUcoマーカを認識してから3秒以上経つとピッキング動作を開始します。

# Any other comments?

# Checklists

- [x]  I have read the CONTRIBUTING guidelines.
    
    - If there is no guideline in the repository, [rt-net organization's guideline](https://github.com/rt-net/.github/blob/master/CONTRIBUTING.md) applies.
- [x]  I have checked to ensure there aren't other open [Pull Requests](../pulls) for the same change.

2022-12-28 09:39 UTC, Kuwamai commented
[aruco_marker.pdf](https://github.com/rt-net/crane_x7_ros/files/10313379/aruco_marker.pdf)
動作確認に使用したマーカはこちらです。

2023-01-10 01:34 UTC, ShotaAk requested changes
コードを見ました。コメントの確認をお願いします。

X7とカメラを個別に動かしたため、ピッキング動作については未確認です。
コメントの指摘事項修正後に動作確認します。

2023-01-17 02:49 UTC, ShotaAk commented on crane_x7_examples/launch/demo.launch.py
> +                ["'", LaunchConfiguration('use_d435'), "' == 'false'"])),
`UnlessCondition`が使えるはずなので、確認してみてください。

https://github.com/ros2/launch/blob/rolling/launch/launch/conditions/unless_condition.py

2023-01-24 02:51 UTC, ShotaAk requested changes

2023-01-24 02:51 UTC, ShotaAk commented on crane_x7_examples/README.md
> +
マーカ位置・姿勢がtarget_0, target_1,,, というtfのフレームでパブリッシュされること、
サンプルでピック&プレースするのはID:0のマーカであることを記載してください。

2023-01-25 02:05 UTC, merged

2023-01-25 02:10 UTC, ShotaAk commented
良いと思います。
foxy & 実機 & CycloneDDS環境で動作確認できたのでマージしました。