Jazzy対応
rt-net/crane_x7_ros pull request #198
Opened 2024-12-26 01:53 UTC by Kuwamai

# What does this implement/fix?

Jazzy対応します

# Does this close any currently open issues?

# How has this been tested?

# Any other comments?

# Checklists

- [x]  I have read the CONTRIBUTING guidelines.
    
    - If there is no guideline in the repository, [rt-net organization's guideline](https://github.com/rt-net/.github/blob/master/CONTRIBUTING.md) applies.
- [x]  I have checked to ensure there aren't other open [Pull Requests](../pulls) for the same change.

2025-01-06 08:16 UTC, YusukeKato commented
Ubuntu 24.04 LTS + ROS 2 Jazzy環境において、Gazebo上ですべてのサンプルが動作することを確認しました（カメラサンプルは除く）。

Gazebo起動時に下記のエラーが出るので共有します。

```
$ ros2 launch crane_x7_gazebo crane_x7_with_table.launch.py
...
[gz sim -r-1] [Err] [Physics.cc:1773] Attempting to create a mimic constraint for joint [crane_x7_gripper_finger_b_joint] but the chosen physics engine does not support mimic constraints, so no constraint will be created.
...
```

2025-01-08 07:00 UTC, YusukeKato requested changes
一か所だけ細かい指摘ですがコメントしましたので確認をお願いします。
その他は問題ないと思います。

2025-01-08 07:00 UTC, YusukeKato commented on .github/workflows/industrial_ci.yml
>        - uses: actions/checkout@v3
```suggestion
      - uses: actions/checkout@v4
```
変更箇所ではありませんが、Checkoutの最新バージョンが4になっているので更新するとよさそうです。
https://github.com/marketplace/actions/checkout

2025-01-08 07:39 UTC, Kuwamai commented on .github/workflows/industrial_ci.yml
>        - uses: actions/checkout@v3
ありがとうございます。commitしました。

2025-01-08 07:51 UTC, Kuwamai commented
> Ubuntu 24.04 LTS + ROS 2 Jazzy環境において、Gazebo上ですべてのサンプルが動作することを確認しました（カメラサンプルは除く）。
> 
> Gazebo起動時に下記のエラーが出るので共有します。
> 
> ```
> $ ros2 launch crane_x7_gazebo crane_x7_with_table.launch.py
> ...
> [gz sim -r-1] [Err] [Physics.cc:1773] Attempting to create a mimic constraint for joint [crane_x7_gripper_finger_b_joint] but the chosen physics engine does not support mimic constraints, so no constraint will be created.
> ...
> ```

こちらのエラーについては動作に問題ないようです。
記録として後ほどissueにまとめようと思います。
https://github.com/rt-net/sciurus17_ros/pull/158#discussion_r1847577254

2025-01-08 07:55 UTC, YusukeKato approved these changes
修正ありがとうございます。
LGTMです！

2025-01-09 09:28 UTC, YusukeKato approved these changes
追加修正を確認しました。
LGTMです！

2025-01-09 09:30 UTC, merged